### ISSUE TITLE
同学校

### ISSUE THREAD

**Issue by tanX9264** [easechen/htu_wifi_login#2]
求博主个联系方式，一起学习，我也有写了一个但是有点问题，希望能帮忙解决一下,206860137 企鹅

**Comment by easechen** [comment]
> 求博主个联系方式，一起学习，我也有写了一个但是有点问题，希望能帮忙解决一下,206860137 企鹅

    很高兴一起交流学习，请联系我的邮箱 relaxxcn@qq.com
谢谢😊

**Comment by tanX9264** [comment]
已发送邮件，请查收
